import Head from "next/head";
import Avatar from "../components/Avatar";
import Image from "next/image";
import { MicrophoneIcon, ViewGridIcon } from "@heroicons/react/solid";
import { SearchIcon } from "@heroicons/react/outline";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Google</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://image.flaticon.com/icons/png/512/281/281781.png"
        />
      </Head>

      {/* header */}

      <header className="flex w-full p-5 justify-between text-sm text-gray-700">
        <div className="flex space-x-4 items-center  ">
          <p className="link">About</p>
          <p className="link">Store</p>
        </div>
        <div className="flex space-x-4 items-center">
          <p className="link">Gmail</p>
          <p className="link">Image</p>
          <ViewGridIcon className="h-10 w-10 p-2 rounded-full hover:bg-gray-100 cursor-pointer" />
          <Avatar
            url={"https://avatars.githubusercontent.com/u/66429052?v=4"}
          />
        </div>
      </header>

      {/* body */}

      <form className="flex flex-col items-center mt-44 flex-grow">
        <Image
          src="https://www.google.co.in/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png"
          height={100}
          width={300}
        />
        <div className="flex w-full mt-5 hover:shadow-lg focus-within:shadow-lg max-w-sm  rounded-full border border-gray-200 px-5 py-3 items-center sm:max-w-xl lg:max-w-2xl">
          <SearchIcon className="h-5  mr-3 text-gray-500" />
          <input type="text" className="focus:outline-none flex-grow " />
          <MicrophoneIcon className="h-5 " />
        </div>

        <div>
          <button className="btn">Google Search</button>
          <button className="btn">I`m Feeling Lucky</button>
        </div>
      </form>

      {/* footer */}
    </div>
  );
}
